### PR TITLE
Fix TaskManager singleton added missing unit tests

### PR DESCRIPTION
**Pull request by DistroRickDev**
Fixe TaskManager singleton added missing unit tests

### CODE REVIEW

**Review by JayBSB — COMMENTED** [review]
On line 9 of TaskManager, the ILogger is of type "ProjectManager" instead of TaskManager. Otherwise lgtm!

**Comment by DistroRickDev** [comment]
> On line 9 of TaskManager, the ILogger is of type "ProjectManager" instead of TaskManager. Otherwise lgtm!

Great catch fixed

**Review by JayBSB — CHANGES_REQUESTED** [review]
lgtm

**Review by JayBSB — APPROVED** [review]
lgtm

**Pull request merged**
